CREATE TABLE ${TABLE_PREFIX}geoname (
    id              integer NOT NULL,
    "name"          text COLLATE pg_catalog."default",
    ascii_name      text COLLATE pg_catalog."default",
    alternate_names TEXT,
    latitude        FLOAT,
    longitude       FLOAT,
    fclass          character varying(1) COLLATE pg_catalog."default",
    fcode           character varying(10) COLLATE pg_catalog."default",
    country         character varying(2) COLLATE pg_catalog."default",
    cc2             text COLLATE pg_catalog."default",
    admin1          text COLLATE pg_catalog."default",
    admin2          text COLLATE pg_catalog."default",
    admin3          text COLLATE pg_catalog."default",
    admin4          text COLLATE pg_catalog."default",
    "population"    bigint,
    elevation       integer,
    gtopo30         integer,
    timezone        text COLLATE pg_catalog."default",
    modified_date   date,
    center          geometry(Geometry,4326),
    search_vector   tsvector
);